# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bands_cpp <- function(mbeta, mbeta2, Bs, beta, alpha) {
    .Call(`_HFMM_bands_cpp`, mbeta, mbeta2, Bs, beta, alpha)
}

hmix_mcmc <- function(y, X, Bs, burnin, nsim, thin, spatial = TRUE) {
    .Call(`_HFMM_hmix_mcmc`, y, X, Bs, burnin, nsim, thin, spatial)
}

vmix_mcmc <- function(y, X, Bs, nfac, burnin, nsim, thin) {
    .Call(`_HFMM_vmix_mcmc`, y, X, Bs, nfac, burnin, nsim, thin)
}

smix_mcmc <- function(y, X, Bs, nfacL, nfacR, burnin, nsim, thin) {
    .Call(`_HFMM_smix_mcmc`, y, X, Bs, nfacL, nfacR, burnin, nsim, thin)
}

